version: '3.9'

name: share-db

services:
  db:
    container_name: db-postgres
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    shm_size: 128mb
    environment:
      POSTGRES_DB: sharedb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  db-test:
    container_name: db-postgres-test
    image: postgres
    restart: always
    ports:
      - '5454:5432'
    shm_size: 128mb
    environment:
      POSTGRES_DB: sharedb-tests
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
